name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup Java / JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: |
          npm install
          npm run data:build

      - name: Build Android App
        run: |
          cd apps/mobile
          npm install
          npx expo prebuild --platform android
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NutAI-Android-APK
          path: apps/mobile/android/app/build/outputs/apk/release/app-release.apk
